#include "dynamic_area.h"

#include "display.h"
#include "enemies.h"

// Generated by scripts/generate-sprites.py at compile time.
#include "dynamic_area-sprites.h"

// Custom characters base offsets in video RAM.
#define FONT_CACTUS_AREA_BASE 0x20  // 15 tiles
#define FONT_BIRD1_AREA_BASE 0x2F   // 15 tiles
#define FONT_BIRD2_AREA_BASE 0x3E   // 15 tiles
#define FONT_ROCK1_AREA_BASE 0x4D   // 15 tiles
#define FONT_ROCK2_AREA_BASE 0x5C   // 15 tiles
#define FONT_DINO_AREA_BASE 0x6B    // DINO_AREA_ROWS*DINO_AREA_COLS tiles

static inline uint8_t sprite_compute_horizontal_shift(
    __code const uint8_t* sprite, uint8_t y, int8_t shift) {
  if (shift >= 0) {
    return sprite[y] << shift;
  } else {
    return sprite[y] >> -shift;
  }
}

static void sprite_load_horizontally_shifted(__code const uint8_t* sprite,
                                             int8_t shift,
                                             uint8_t destination_index) {
  for (uint8_t y = 0; y < 10; y++) {
    display_load_scanline(destination_index, y,
                          sprite_compute_horizontal_shift(sprite, y, shift));
  }
}

// Loads all the sprites.
void dynamic_area_init(void) {
  for (int8_t shift = -7; shift < 8; shift++) {
    sprite_load_horizontally_shifted(CACTUS, shift,
                                     FONT_CACTUS_AREA_BASE + 7 + shift);
  }
  for (int8_t shift = -7; shift < 8; shift++) {
    sprite_load_horizontally_shifted(BIRD1, shift,
                                     FONT_BIRD1_AREA_BASE + 7 + shift);
  }
  for (int8_t shift = -7; shift < 8; shift++) {
    sprite_load_horizontally_shifted(BIRD2, shift,
                                     FONT_BIRD2_AREA_BASE + 7 + shift);
  }
  for (int8_t shift = -7; shift < 8; shift++) {
    sprite_load_horizontally_shifted(ROCK1, shift,
                                     FONT_ROCK1_AREA_BASE + 7 + shift);
  }
  for (int8_t shift = -7; shift < 8; shift++) {
    sprite_load_horizontally_shifted(ROCK2, shift,
                                     FONT_ROCK2_AREA_BASE + 7 + shift);
  }
}

void dynamic_area_clear(void) {
  // Copy row 1, which we know is a blank line, over where the enemies might be
  // drawn to clear the area before we proceed to actually draw them.
  for (uint8_t i = 0; i < ENEMY_AREA_ROWS; i++) {
    uint8_t row = ENEMY_BASE_ROW - i;
    display_copy_line(1, row);
  }

  // Clear the top of the dino area too. Note that the bottom part has already
  // been cleared by the previous loop.
  for (uint8_t i = ENEMY_AREA_ROWS; i < DINO_AREA_ROWS; i++) {
    uint8_t row = ENEMY_BASE_ROW - i;
    display_write_char(DINO_LEADING_COL, row, 0x70, 0x00, ' ');
    display_write_char(DINO_LEADING_COL + 1, row, 0x70, 0x00, ' ');
  }
}

void dynamic_area_draw_enemies(__data IntersectingEnemyInfo* intersection) {
  for (uint8_t i = 0; i < DINO_AREA_COLS; ++i) {
    intersection->sprites[i] = NULL;
  }

  for (uint8_t i = 0; i < ENEMIES_SIZE; ++i) {
    uint16_t wrapping_x = FIXED_POINT_GET_INTEGRAL_PART(enemies[i].x);
    uint8_t leading_column = wrapping_x / 8;
    uint8_t shift = wrapping_x % 8;

    uint8_t index;
    __code const uint8_t* sprite;

    switch (enemies[i].type) {
      case ENEMY_CACTUS:
        index = FONT_CACTUS_AREA_BASE + 7 + shift;
        sprite = CACTUS;
        break;
      case ENEMY_BIRD:
        if (leading_column % 4 < 2) {
          index = FONT_BIRD1_AREA_BASE + 7 + shift;
          sprite = BIRD1;
        } else {
          index = FONT_BIRD2_AREA_BASE + 7 + shift;
          sprite = BIRD2;
        }
        break;
      case ENEMY_ROCK1:
        index = FONT_ROCK1_AREA_BASE + 7 + shift;
        sprite = ROCK1;
        break;
      case ENEMY_ROCK2:
        index = FONT_ROCK2_AREA_BASE + 7 + shift;
        sprite = ROCK2;
        break;
      default:
        continue;
    }

    uint8_t row = ENEMY_BASE_ROW - enemies[i].row;

    // The enemy might fit in just one tile (if perfectly aligned to the grid),
    // or it might need two tiles. This block draws the left tile. The other
    // one, if needed, will be drawn later.
    // Note: if the tile is in the dine area, it will actually be drawn by
    // draw_dino() using the info stored in "intersection".
    if (leading_column < DINO_LEADING_COL ||
        leading_column >= DINO_LEADING_COL + DINO_AREA_COLS) {
      if (leading_column < DISPLAY_COLS) {
        display_write_char(leading_column, row, 0x70, 0x80, index);
      }
    } else {
      intersection->sprites[leading_column - DINO_LEADING_COL] = sprite;
      intersection->shifts[leading_column - DINO_LEADING_COL] = shift;
      intersection->rows[leading_column - DINO_LEADING_COL] = row;
    }

    // Draw the other tile, if needed.
    if (shift != 0) {
      uint8_t trailing_column = leading_column + 1;
      if (trailing_column < DINO_LEADING_COL ||
          trailing_column >= DINO_LEADING_COL + DINO_AREA_COLS) {
        if (trailing_column < DISPLAY_COLS) {
          display_write_char(trailing_column, row, 0x70, 0x80, index - 8);
        }
      } else {
        intersection->sprites[trailing_column - DINO_LEADING_COL] = sprite;
        intersection->shifts[trailing_column - DINO_LEADING_COL] = shift - 8;
        intersection->rows[trailing_column - DINO_LEADING_COL] = row;
      }
    }
  }
}

bool dynamic_area_draw_dino(uint8_t dino_y,
                            __data const IntersectingEnemyInfo* intersection,
                            bool feet_toggle) {
  bool hit = false;

  uint16_t char_index = FONT_DINO_AREA_BASE;
  for (uint8_t r = ENEMY_BASE_ROW - DINO_AREA_ROWS; r++ < ENEMY_BASE_ROW;) {
    display_set_profiling_color(ENEMY_BASE_ROW - r);
    for (uint8_t c = DINO_LEADING_COL; c < DINO_LEADING_COL + DINO_AREA_COLS;
         ++c) {
      __code const uint8_t* dino_sprite;
      if (feet_toggle)
        dino_sprite = c == DINO_LEADING_COL ? DINO1_LEADING : DINO1_TRAILING;
      else
        dino_sprite = c == DINO_LEADING_COL ? DINO2_LEADING : DINO2_TRAILING;

      __code const uint8_t* enemy_sprite =
          intersection->sprites[c - DINO_LEADING_COL];
      int8_t enemy_shift = intersection->shifts[c - DINO_LEADING_COL];

      int8_t dino_offset_in_sprite = dino_y - (ENEMY_BASE_ROW - r) * 10;
      int8_t enemy_offset_in_sprite =
          enemy_sprite == NULL
              ? -10  // out of range, makes the next checks skip this sprite
              : (r - intersection->rows[c - DINO_LEADING_COL]) * 10;
      bool no_dino =
          dino_offset_in_sprite + 10 <= 0 || dino_offset_in_sprite >= 10;
      bool no_enemy =
          enemy_offset_in_sprite + 10 <= 0 || enemy_offset_in_sprite >= 10;
      if (!no_dino || !no_enemy) {
        display_write_char(c, r, 0x70, 0x80, char_index);

        for (uint8_t y = 0; y < 10;
             ++y, ++dino_offset_in_sprite, ++enemy_offset_in_sprite) {
          uint8_t dino_pixels = 0;
          if (dino_offset_in_sprite >= 0 && dino_offset_in_sprite < 10)
            dino_pixels = dino_sprite[dino_offset_in_sprite];

          uint8_t enemy_pixels = 0;
          if (enemy_offset_in_sprite >= 0 && enemy_offset_in_sprite < 10)
            enemy_pixels =
                sprite_compute_horizontal_shift(enemy_sprite, y, enemy_shift);

          display_load_scanline(char_index, y, dino_pixels | enemy_pixels);

          // Ignore collisions in lower four pixel lines, to filter out rocks.
          if ((dino_pixels & enemy_pixels) &&
              !(r == ENEMY_BASE_ROW && y >= 6)) {
            hit = true;
          }
        }
      }

      char_index++;
    }
  }

  return hit;
}
