#include "floor_area.h"

#include "display.h"

// Generated by scripts/generate-floor.py at compile time.
#include "floor_area-slices.h"

// Custom characters base offset in video RAM.
#define FONT_FLOOR_AREA_BASE 0x0

#define LUT_PERIOD 32  // 4 characters * 8 pixels

static fixed_point_t floor_x = 0;

void floor_area_init(void) {
  for (uint8_t char_index = 0; char_index < 4; char_index++) {
    for (uint8_t y = 0; y < 10; y++) {
      display_load_scanline(char_index, y, y == 0 ? 0xff : 0);
    }
  }

  for (uint8_t x = 0; x < DISPLAY_COLS; x += 4) {
    display_write_text(x, FLOOR_ROW, 0x70, 0x80, "\x00\x01\x02\x03");
  }

  floor_x = 0;
}

static inline void update_scanline(uint8_t y, uint8_t rotation) {
  rotation %= 32;
  display_load_scanline(0, y, FLOOR_LUT_A[rotation]);
  display_load_scanline(1, y, FLOOR_LUT_B[rotation]);
  display_load_scanline(2, y, FLOOR_LUT_C[rotation]);
  display_load_scanline(3, y, FLOOR_LUT_D[rotation]);
}

void floor_area_draw(void) {
  uint8_t rotation = FIXED_POINT_GET_INTEGRAL_PART(floor_x);
  update_scanline(3, rotation);
  update_scanline(5, rotation + 16);
}

void floor_area_update(fixed_point_t dino_speed) { floor_x -= dino_speed; }
