#include "splash.h"

#include "display.h"

// Generated by scripts/generate-splash.py at compile time.
#include "splash-tiles.h"

#define SPLASH_OFFSET_ROW 1

void splash_draw(void) {
  display_clear_screen(0x00);

  // Render the splashscreen.
  __code uint8_t* read_pos = SPLASH_DATA;
  uint8_t char_index = 0;
  for (uint8_t y = 0; y < SPLASH_ROWS; y++) {
    for (uint8_t x = 0; x < SPLASH_COLS; x++) {
      uint8_t marker = *read_pos++;
      if (marker == 0) {
        display_write_char(2 * x + 0, SPLASH_OFFSET_ROW + y, 0x70, 0x08, ' ');
        display_write_char(2 * x + 1, SPLASH_OFFSET_ROW + y, 0x70, 0x08, ' ');
      } else if (marker == 1) {
        display_write_char(2 * x + 0, SPLASH_OFFSET_ROW + y, 0x07, 0x08, ' ');
        display_write_char(2 * x + 1, SPLASH_OFFSET_ROW + y, 0x07, 0x08, ' ');
      } else {
        for (uint8_t i = 0; i < 10; i++) {
          display_load_scanline(char_index, i, *read_pos++);
        }

        display_write_char(2 * x + 0, SPLASH_OFFSET_ROW + y, 0x70, 0x88,
                           char_index);
        display_write_char(2 * x + 1, SPLASH_OFFSET_ROW + y, 0x70, 0x88,
                           char_index);

        // Move to the next character definitions, taking into account the gap
        // between 4 and 32.
        if (++char_index == 4) {
          char_index = 32;
        }
      }
    }
  }

  // Overlay text on top.
  display_write_text(0, 4, 0x70, 0x08, "PPrreessss");
  display_write_char(11, 4, 0x02, 0, ' ');
  display_write_text(12, 4, 0x02, 0x08, "SSppaaccee");
  display_write_char(22, 4, 0x02, 0, ' ');
  display_write_text(24, 4, 0x70, 0x08, "ttoo  ppllaayy!!");

  display_write_char(0, 12, 0x02, 0, ' ');
  display_write_text(1, 12, 0x02, 0x08, "\x5e\x5e" /* arrow up character */);
  display_write_char(3, 12, 0x02, 0, ' ');
  display_write_text(5, 12, 0x60, 0x08, "JJuummpp");

  display_write_char(21, 12, 0x02, 0, ' ');
  display_write_text(22, 12, 0x02, 0x08, "EEsscc");
  display_write_char(28, 12, 0x02, 0, ' ');
  display_write_text(30, 12, 0x60, 0x08, "PPaauussee");
}
