#include "static_area.h"

#include "display.h"
#include "dynamic_area.h"
#include "enemies.h"

// Generated by scripts/generate-sprites.py at compile time.
#include "static_area-sprites.h"

// Custom characters base offsets in video RAM.
#define FONT_CLOUD1L 0x75
#define FONT_CLOUD1M 0x76
#define FONT_CLOUD1R 0x77
#define FONT_CLOUD2A 0x78
#define FONT_CLOUD2BTL 0x79
#define FONT_CLOUD2BTR 0x7A
#define FONT_CLOUD2BBL 0x7B
#define FONT_CLOUD2BBR 0x7C
#define FONT_STAR1 0x7D
#define FONT_STAR2 0x7E
#define FONT_STAR3 0x7F

#define COLOR_VERY_BRIGHT 0x70
#define COLOR_BRIGHT 0x30
#define COLOR_DIM 0x20

static void sprite_load(__code const uint8_t* sprite,
                        uint8_t destination_index) {
  for (uint8_t y = 0; y < 10; y++) {
    display_load_scanline(destination_index, y, sprite[y]);
  }
}

// Loads all the sprites.
void static_area_init(void) {
  // Common tiles of the cloud (3 leftmost ones).
  sprite_load(CLOUD1L, FONT_CLOUD1L);
  sprite_load(CLOUD1M, FONT_CLOUD1M);
  sprite_load(CLOUD1R, FONT_CLOUD1R);

  // Normal cloud righmost tile.
  sprite_load(CLOUD2A, FONT_CLOUD2A);

  // Cloud with moon, 2x2 square alternative to the righmost tile.
  sprite_load(CLOUD2BTL, FONT_CLOUD2BTL);
  sprite_load(CLOUD2BTR, FONT_CLOUD2BTR);
  sprite_load(CLOUD2BBL, FONT_CLOUD2BBL);
  sprite_load(CLOUD2BBR, FONT_CLOUD2BBR);

  // Stars (3 types).
  sprite_load(STAR1, FONT_STAR1);
  sprite_load(STAR2, FONT_STAR2);
  sprite_load(STAR3, FONT_STAR3);
}

static void draw_cloud(uint8_t x, uint8_t y, bool with_moon) {
  display_write_char(x + 0, y, COLOR_DIM, 0x88, FONT_CLOUD1L);
  display_write_char(x + 1, y, COLOR_DIM, 0x88, FONT_CLOUD1L);
  display_write_char(x + 2, y, COLOR_DIM, 0x88, FONT_CLOUD1M);
  display_write_char(x + 3, y, COLOR_DIM, 0x88, FONT_CLOUD1M);
  display_write_char(x + 4, y, COLOR_DIM, 0x88, FONT_CLOUD1R);
  display_write_char(x + 5, y, COLOR_DIM, 0x88, FONT_CLOUD1R);
  if (with_moon == false) {
    display_write_char(x + 6, y, COLOR_DIM, 0x88, FONT_CLOUD2A);
    display_write_char(x + 7, y, COLOR_DIM, 0x88, FONT_CLOUD2A);
  } else {
    display_write_char(x + 6, y, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BTL);
    display_write_char(x + 7, y, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BTL);
    display_write_char(x + 8, y, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BTR);
    display_write_char(x + 9, y, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BTR);
    display_write_char(x + 6, y + 1, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BBL);
    display_write_char(x + 7, y + 1, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BBL);
    display_write_char(x + 8, y + 1, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BBR);
    display_write_char(x + 9, y + 1, COLOR_VERY_BRIGHT, 0x88, FONT_CLOUD2BBR);
  }
}

static void draw_star(uint8_t x, uint8_t y, uint8_t type) {
  uint8_t font_index;
  switch (type) {
    case 1:
      font_index = FONT_STAR1;
      break;
    case 2:
      font_index = FONT_STAR2;
      break;
    case 3:
      font_index = FONT_STAR3;
      break;
  }

  display_write_char(x + 0, y, COLOR_BRIGHT, 0x88, font_index);
  display_write_char(x + 1, y, COLOR_BRIGHT, 0x88, font_index);
}

void static_area_draw(void) {
  draw_star(0, 2, 3);
  draw_cloud(3, 4, false);
  draw_star(10, 3, 1);
  draw_star(20, 2, 2);
  draw_star(21, 3, 3);
  draw_cloud(30, 2, true);
  draw_star(34, 3, 3);
  draw_star(29, 4, 2);

  draw_star(2, 7, 1);
  draw_star(3, 6, 3);
  draw_star(38, 6, 3);
}
