#ifndef LIB_BOARD_NFZ400_INCLUDE_BOARD_DEFINITIONS_H
#define LIB_BOARD_NFZ400_INCLUDE_BOARD_DEFINITIONS_H

#include <stdint.h>

#define XTAL_HZ 14318180

#define VIDEO_TS9347
#define VIDEO_MCU_INTERFACE_BASE_ADDRESS 0x4020
#define VIDEO_TGS_BOARD_EXTRAS VIDEO_TGS_SERVICE_OUTPUT_P2P1HVS_NP
#define VIDEO_PAT_BOARD_EXTRAS VIDEO_PAT_PORT1_NP  // Turns the red LED on.

#define KEYBOARD_ROWS 9
uint8_t board_read_keyboard(uint8_t row);

#endif
