#!/usr/bin/env python3
import sys
from typing import Dict, Iterable, Tuple


def read_keymap(path: str) -> Dict[Tuple[int, int], str]:
    keymap = dict()
    row = 0
    with open(path, "rt") as fp:
        for line in map(str.strip, fp):
            # Ignore empty and comment lines
            if not line or line.startswith("#"):
                continue
            b7, b6, b5, b4, b3, b2, b1, b0 = line.split()
            if b0 != "-":
                keymap[row, 0] = b0
            if b1 != "-":
                keymap[row, 1] = b1
            if b2 != "-":
                keymap[row, 2] = b2
            if b3 != "-":
                keymap[row, 3] = b3
            if b4 != "-":
                keymap[row, 4] = b4
            if b5 != "-":
                keymap[row, 5] = b5
            if b6 != "-":
                keymap[row, 6] = b6
            if b7 != "-":
                keymap[row, 7] = b7
            row += 1

    if len(set(keymap.values())) != len(keymap):
        exit("Error! A key was defined more than once in the keymap")

    # Error if the name would not fit in the "hello_world" displayed text.
    for name in keymap.values():
        if len(name) > 13:
            exit("Error! A key has a too long name")

    return keymap


def write_keylist_file(keylist: Iterable[str], path: str):
    with open(path, "wt") as fp:
        print("// Automatically generated by generate_keyboard_map.py", file=fp)
        for name in keylist:
            print(f"KEYLIST_ENTRY({name})", file=fp)


def write_keymap_file(keymap: Dict[Tuple[int, int], str], path: str):
    with open(path, "wt") as fp:
        print("// Automatically generated by generate_keyboard_map.py", file=fp)
        for (row, column), name in keymap.items():
            print(
                f"#define KEY_{name} KEYBOARD_MAKE_KEY_CODE({row}, {column})",
                file=fp,
            )


def main():
    input_txt = sys.argv[1]
    output_keylist = sys.argv[2]
    output_keymap = sys.argv[3]

    keymap = read_keymap(input_txt)
    write_keylist_file(keymap.values(), output_keylist)
    write_keymap_file(keymap, output_keymap)


if __name__ == "__main__":
    main()
