#!/usr/bin/env python3
import sys
from typing import Dict, Iterable, TextIO, Tuple

MAX_NAME_LEN = 12


def read_keymatrix(fp: TextIO) -> Dict[Tuple[int, int], str]:
    keymatrix = dict()
    row = 0
    for line in map(str.strip, fp):
        # Ignore empty and comment lines
        if not line or line.startswith("#"):
            continue
        b7, b6, b5, b4, b3, b2, b1, b0 = line.split()
        if b0 != "-":
            keymatrix[row, 0] = b0
        if b1 != "-":
            keymatrix[row, 1] = b1
        if b2 != "-":
            keymatrix[row, 2] = b2
        if b3 != "-":
            keymatrix[row, 3] = b3
        if b4 != "-":
            keymatrix[row, 4] = b4
        if b5 != "-":
            keymatrix[row, 5] = b5
        if b6 != "-":
            keymatrix[row, 6] = b6
        if b7 != "-":
            keymatrix[row, 7] = b7
        row += 1

    if len(set(keymatrix.values())) != len(keymatrix):
        exit("Error! A key was defined more than once in the keymap")

    # Error if the name would not fit in the "hello_world" displayed text.
    for name in keymatrix.values():
        if len(name) > MAX_NAME_LEN:
            exit("Error! A key has a too long name")

    return keymatrix


def read_keyenum(fp: TextIO) -> Dict[int, str]:
    keyenum = dict()
    for line in map(str.strip, fp):
        # Ignore empty and comment lines
        if not line or line.startswith("#"):
            continue
        value_str, name = line.split(":")
        value = int(value_str, 16)
        if value in keyenum.keys():
            exit("Error! A key was defined more than once in the keymap")
        keyenum[value] = name

    if len(set(keyenum.values())) != len(keyenum):
        exit("Error! A key was defined more than once in the keymap")

    # Error if the name would not fit in the "hello_world" displayed text.
    for name in keyenum.values():
        if len(name) > MAX_NAME_LEN:
            exit("Error! A key has a too long name")

    return keyenum


def write_keylist_file(keylist: Iterable[str], path: str):
    with open(path, "wt") as fp:
        print("// Automatically generated by generate_keyboard_map.py", file=fp)
        for name in keylist:
            print(f"KEYLIST_ENTRY({name})", file=fp)


def write_keymatrix_file(keymatrix: Dict[Tuple[int, int], str], path: str):
    with open(path, "wt") as fp:
        print("// Automatically generated by generate_keyboard_map.py", file=fp)
        for (row, column), name in keymatrix.items():
            print(
                f"#define KEY_{name} KEYBOARD_MAKE_KEY_CODE({row}, {column})",
                file=fp,
            )


def write_keyenum_file(keymatrix: Dict[Tuple[int, int], str], path: str):
    with open(path, "wt") as fp:
        print("// Automatically generated by generate_keyboard_map.py", file=fp)
        for value, name in keymatrix.items():
            print(
                f"#define KEY_{name} 0x{value:02x}",
                file=fp,
            )


def main():
    input_txt = sys.argv[1]
    output_keylist = sys.argv[2]
    output_keymap = sys.argv[3]

    with open(input_txt, "rt") as fp:
        kind = fp.readline()

        match kind:
            case "@!KEYBOARD_MATRIX\n":
                keymatrix = read_keymatrix(fp)
                write_keylist_file(keymatrix.values(), output_keylist)
                write_keymatrix_file(keymatrix, output_keymap)
            case "@!KEYBOARD_ENUM\n":
                keyenum = read_keyenum(fp)
                write_keylist_file(keyenum.values(), output_keylist)
                write_keyenum_file(keyenum, output_keymap)
            case _:
                exit("Found no annotation selecting the kind of keyboard")


if __name__ == "__main__":
    main()
